"""Element discovery types + the JS payload Playwright evaluates.

The discovery script runs once per snapshot. It returns a flat list of
records describing every visible, actionable element on the page —
links, buttons, every form control, every ``[role]`` Playwright treats
as actionable, plus a catch-all for ``[onclick]`` / ``tabindex``. The
Python side classifies each record into an :class:`ElementKind` so the
filter checkboxes can narrow the list without a second DOM round-trip.

The JS lives here as a string constant rather than a static asset so
unit tests can assert on the exact payload (and so a future bundling
step doesn't have to package extra files).
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class ElementKind(str, Enum):
    """Coarse-grained classification driving the filter checkboxes."""

    LINK = "link"
    BUTTON = "button"
    INPUT = "input"
    CHECKBOX_RADIO = "checkbox_radio"
    SELECT = "select"
    MENU = "menu"
    TAB = "tab"
    HEADING = "heading"
    OTHER = "other"

    @property
    def label(self) -> str:
        return _KIND_LABELS[self]


_KIND_LABELS = {
    ElementKind.LINK: "Links",
    ElementKind.BUTTON: "Buttons",
    ElementKind.INPUT: "Inputs",
    ElementKind.CHECKBOX_RADIO: "Checkbox / Radio",
    ElementKind.SELECT: "Selects & Dropdowns",
    ElementKind.MENU: "Menu items",
    ElementKind.TAB: "Tabs",
    ElementKind.HEADING: "Headings",
    ElementKind.OTHER: "Other",
}


@dataclass(frozen=True)
class WebElement:
    """One actionable element discovered on a page snapshot.

    All coordinates are in CSS pixels relative to the document origin
    (``page.evaluate``'s view). The IDE overlay scales by
    ``device_pixel_ratio`` when projecting onto the captured PNG; the
    asset cropper does the same when slicing the BGR frame.
    """

    kind: ElementKind
    role: str
    """ARIA role or HTML tag — ``"button"``, ``"link"``, ``"textbox"``."""
    name: str
    """Accessible name — ``aria-label``, ``alt``, button text, etc."""
    selector: str
    """A CSS selector good enough to re-locate the element on a reload.
    Generated by the discovery JS using id / data-testid / class chain
    + nth-of-type fallback."""
    xpath: str
    """Document-order XPath; useful as a tiebreaker when CSS isn't unique."""
    bounds: tuple[float, float, float, float]
    """``(x, y, w, h)`` in CSS pixels; ``w == 0`` or ``h == 0`` means
    the element was hidden at snapshot time and should be filtered out."""
    tag: str = ""
    """Lowercased HTML tag (``"a"``, ``"button"``, ``"input"``)."""
    type: str = ""
    """``input``'s ``type`` attribute when relevant; empty otherwise."""

    @property
    def visible(self) -> bool:
        return self.bounds[2] > 0 and self.bounds[3] > 0

    @property
    def display_name(self) -> str:
        """Single-line label for the sidebar list."""
        name = (self.name or "").strip()
        if not name:
            # Fall back to a short fragment of the selector so list rows
            # never end up blank.
            return self.selector[:48]
        # Collapse internal whitespace so list rows stay one line.
        return " ".join(name.split())[:80]

    @property
    def display_role(self) -> str:
        """Pretty role token for the sidebar — ``[button]`` etc."""
        return self.role or self.tag or "element"


def classify(tag: str, type_attr: str, role: str) -> ElementKind:
    """Map a discovery record to an :class:`ElementKind`.

    The discovery JS already filters out non-actionable elements, so
    everything that lands here belongs in *some* bucket — ``OTHER``
    catches the catch-all (custom ``[onclick]`` / ``tabindex`` widgets).
    """
    tag = (tag or "").lower()
    type_attr = (type_attr or "").lower()
    role = (role or "").lower()

    if tag == "a" and role in {"", "link"}:
        return ElementKind.LINK
    if role == "link":
        return ElementKind.LINK

    if tag == "button" or role == "button":
        return ElementKind.BUTTON
    if tag == "input" and type_attr in {"button", "submit", "reset", "image"}:
        return ElementKind.BUTTON

    if tag == "input" and type_attr in {"checkbox", "radio"}:
        return ElementKind.CHECKBOX_RADIO
    if role in {"checkbox", "radio", "switch"}:
        return ElementKind.CHECKBOX_RADIO

    if tag == "select" or role in {"combobox", "listbox"}:
        return ElementKind.SELECT

    if tag == "textarea":
        return ElementKind.INPUT
    if tag == "input":
        # Default <input> is text-like; covers text/email/password/tel/url/...
        return ElementKind.INPUT
    if role in {"textbox", "searchbox", "spinbutton"}:
        return ElementKind.INPUT

    if role == "tab":
        return ElementKind.TAB
    if role in {"menuitem", "menuitemcheckbox", "menuitemradio", "option"}:
        return ElementKind.MENU
    if tag == "summary":
        return ElementKind.MENU

    if tag in {"h1", "h2", "h3", "h4", "h5", "h6"} or role == "heading":
        return ElementKind.HEADING

    return ElementKind.OTHER


# ---------------------------------------------------------------------------
# Discovery JS — runs inside Playwright via ``page.evaluate``.
# ---------------------------------------------------------------------------

# The script returns a list of records. Each record carries the raw
# tag/type/role + bounding rect; classification happens on the Python
# side so a unit test can pin both halves independently.
DISCOVERY_JS = r"""
(() => {
  const SELECTOR = [
    'a[href]',
    'button',
    'input',
    'textarea',
    'select',
    'summary',
    '[role="button"]',
    '[role="link"]',
    '[role="checkbox"]',
    '[role="radio"]',
    '[role="switch"]',
    '[role="combobox"]',
    '[role="listbox"]',
    '[role="textbox"]',
    '[role="searchbox"]',
    '[role="spinbutton"]',
    '[role="menuitem"]',
    '[role="menuitemcheckbox"]',
    '[role="menuitemradio"]',
    '[role="option"]',
    '[role="tab"]',
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
    '[role="heading"]',
    '[onclick]',
    '[tabindex]:not([tabindex="-1"])',
  ].join(',');

  function visible(el) {
    if (el.offsetParent === null && getComputedStyle(el).position !== 'fixed') {
      return false;
    }
    const r = el.getBoundingClientRect();
    if (r.width <= 1 || r.height <= 1) return false;
    if (el.getAttribute('aria-hidden') === 'true') return false;
    const cs = getComputedStyle(el);
    if (cs.visibility === 'hidden' || cs.display === 'none') return false;
    return true;
  }

  function accessibleName(el) {
    const aria = el.getAttribute('aria-label');
    if (aria) return aria;
    const labelledby = el.getAttribute('aria-labelledby');
    if (labelledby) {
      const ref = document.getElementById(labelledby);
      if (ref) return (ref.textContent || '').trim();
    }
    if (el.tagName === 'INPUT' && el.placeholder) return el.placeholder;
    if (el.tagName === 'INPUT' && el.value && (el.type === 'submit' || el.type === 'button')) {
      return el.value;
    }
    if (el.alt) return el.alt;
    if (el.title) return el.title;
    return (el.textContent || '').trim();
  }

  function cssPath(el) {
    if (el.id) return '#' + CSS.escape(el.id);
    const dt = el.getAttribute('data-testid');
    if (dt) return `[data-testid="${dt}"]`;
    const parts = [];
    let cur = el;
    while (cur && cur.nodeType === 1 && parts.length < 5) {
      let part = cur.tagName.toLowerCase();
      if (cur.classList.length) {
        const cls = Array.from(cur.classList).slice(0, 2)
          .map((c) => '.' + CSS.escape(c)).join('');
        part += cls;
      }
      const parent = cur.parentElement;
      if (parent) {
        const sib = Array.from(parent.children).filter(
          (n) => n.tagName === cur.tagName,
        );
        if (sib.length > 1) {
          const idx = sib.indexOf(cur) + 1;
          part += ':nth-of-type(' + idx + ')';
        }
      }
      parts.unshift(part);
      cur = parent;
    }
    return parts.join(' > ');
  }

  function xpathOf(el) {
    if (el.id) return `//*[@id="${el.id}"]`;
    const segs = [];
    let cur = el;
    while (cur && cur.nodeType === 1) {
      let idx = 1;
      let sib = cur.previousElementSibling;
      while (sib) {
        if (sib.tagName === cur.tagName) idx += 1;
        sib = sib.previousElementSibling;
      }
      segs.unshift(cur.tagName.toLowerCase() + '[' + idx + ']');
      cur = cur.parentElement;
    }
    return '/' + segs.join('/');
  }

  const seen = new Set();
  const out = [];
  document.querySelectorAll(SELECTOR).forEach((el) => {
    if (seen.has(el)) return;
    seen.add(el);
    if (!visible(el)) return;
    const r = el.getBoundingClientRect();
    out.push({
      tag: el.tagName.toLowerCase(),
      type: (el.getAttribute('type') || '').toLowerCase(),
      role: (el.getAttribute('role') || '').toLowerCase(),
      name: accessibleName(el),
      selector: cssPath(el),
      xpath: xpathOf(el),
      bounds: [r.x + window.scrollX, r.y + window.scrollY, r.width, r.height],
    });
  });
  return {
    devicePixelRatio: window.devicePixelRatio || 1,
    documentSize: [
      Math.max(document.documentElement.scrollWidth, window.innerWidth),
      Math.max(document.documentElement.scrollHeight, window.innerHeight),
    ],
    elements: out,
  };
})()
"""


def from_record(rec: dict) -> WebElement:
    """Build a :class:`WebElement` from a single discovery JS record."""
    tag = (rec.get("tag") or "").lower()
    type_attr = (rec.get("type") or "").lower()
    role = (rec.get("role") or "").lower()
    bounds = rec.get("bounds") or [0, 0, 0, 0]
    if len(bounds) != 4:
        bounds = [0, 0, 0, 0]
    return WebElement(
        kind=classify(tag, type_attr, role),
        role=role or tag or "element",
        name=str(rec.get("name") or ""),
        selector=str(rec.get("selector") or ""),
        xpath=str(rec.get("xpath") or ""),
        bounds=(float(bounds[0]), float(bounds[1]), float(bounds[2]), float(bounds[3])),
        tag=tag,
        type=type_attr,
    )
